font_family       JetBrainsMono Nerd Font Mono
bold_font			auto
italic_font			auto
bold_italic_font	auto
disable_ligatures always

# cursor
cursor_shape		beam
scrollback_lines	9999

# url
detect_urls yes
# url_color #0087bd
url_style curly

#background

background_opacity 0.7

# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME

allow_remote_control yes
listen_on unix:/tmp/kitty

map  ctrl+enter      send_text normal,application \x1b[13;5u
map  shift+enter     send_text normal,application \x1b[13;2u
map  ctrl+tab        send_text normal,application \x1b[9;5u
map  ctrl+shift+left
map  ctrl+shift+right
