#!/usr/bin/env zsh

# ez-compinit cache compdef every 20h. use `compinit` to force load new compdef
zstyle ':plugin:ez-compinit' 'use-cache' 'yes'
zstyle ':plugin:ez-compinit' 'compstyle' 'ohmy'

# autocomplete pattern
# 0 -- vanilla completion (abc => abc)
# 1 -- smart case completion (abc => Abc)
# 2 -- word flex completion (abc => A-big-Car)
# 3 -- full flex completion (abc => ABraCadabra)
zstyle ':completion:*' matcher-list '' \
  'm:{a-z\-}={A-Z\_}' \
  'r:[^[:alpha:]]||[[:alpha:]]=** r:|=* m:{a-z\-}={A-Z\_}' \
  'r:|?=** m:{a-z\-}={A-Z\_}'
# fzf-tab does not work with escape sequences (like '%F{red}%d%f')
# zstyle ':completion:*:*:*:*:descriptions' format '%F{green}-- %d --%f'
# force zsh not to show completion menu, which allows fzf-tab to capture the unambiguous prefix
zstyle ':completion:*' menu no
# set list-colors to enable filename colorizing
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'lsd -1 --color=always $realpath'
zstyle ':fzf-tab:complete:z:*' fzf-preview 'lsd -1 --color=always $realpath'
zstyle ':fzf-tab:complete:nvim:*' fzf-preview '~/.config/zsh/_ftb_preview_path.zsh $realpath'
zstyle ':completion:*' group-name ''

compdef directories z
compdef v=nvim
